@echo off
echo Starting Horizon App Development Server...
start "Horizon Dev Server" cmd /c "npm run dev"
echo Waiting for server to initialize...
timeout /t 3 /nobreak > NUL
echo Opening browser...
start http://localhost:5173
